Fix build with tensorflow toolchain
Due to https://bugs.swift.org/browse/TF-1203, there's a build failure
without this patch:

```
error: static member 'pow' cannot be used on instance of type 'Double'
```